module ParamsHelper

  # This method is called before the search_as_hidden_fields method to wipe
  # out any parameters that are "unknown" to the application.  This should
  # resolve the cross-site scripting warning generated by UC's Hailstorm scan.

  def scrub_params(params)
    safe_params = Hash.new;

    unless params["f"].nil?
      safe_params["f"] = Hash.new;
      safe_params["f"]["desc_metadata__creator_sim"] = params["f"]["desc_metadata__creator_sim"]
      safe_params["f"]["desc_metadata__language_sim"] = params["f"]["desc_metadata__language_sim"]
      safe_params["f"]["desc_metadata__publisher_sim"] = params["f"]["desc_metadata__publisher_sim"]
      safe_params["f"]["desc_metadata__subject_sim"] = params["f"]["desc_metadata__subject_sim"]
      safe_params["f"]["generic_type_sim"] = params["f"]["generic_type_sim"]
      safe_params["f"]["human_readable_type_sim"] = params["f"]["human_readable_type_sim"]
    end

    safe_params["controller"] = params["controller"]
    safe_params["action"] = params["action"]
    safe_params["works"] = params["works"]

    params.clear

    unless safe_params["f"].nil?
      params["f"] = Hash.new
      params["f"]["desc_metadata__creator_sim"] = safe_params["f"]["desc_metadata__creator_sim"] unless safe_params["f"]["desc_metadata__creator_sim"].nil?
      params["f"]["desc_metadata__language_sim"] = safe_params["f"]["desc_metadata__language_sim"] unless safe_params["f"]["desc_metadata__language_sim"].nil?
      params["f"]["desc_metadata__publisher_sim"] = safe_params["f"]["desc_metadata__publisher_sim"] unless safe_params["f"]["desc_metadata__publisher_sim"].nil?
      params["f"]["desc_metadata__subject_sim"] = safe_params["f"]["desc_metadata__subject_sim"] unless safe_params["f"]["desc_metadata__subject_sim"].nil?
      params["f"]["generic_type_sim"] = safe_params["f"]["generic_type_sim"] unless safe_params["f"]["generic_type_sim"].nil?
      params["f"]["human_readable_type_sim"] = safe_params["f"]["human_readable_type_sim"] unless safe_params["f"]["human_readable_type_sim"].nil?
    end

    params["controller"] = safe_params["controller"] unless safe_params["controller"].nil?
    params["action"] = safe_params["action"] unless safe_params["action"].nil?
    params["works"] = safe_params["works"] unless safe_params["works"].nil?
  end

end
